export type jsonFootball = {
    "id": string,
    "country": string,
    "league": string,
    "round": string,
    "S1": number,
    "S2": number,
    "SD": number,
    "ET": string,
    "date": string,
    "time": string,
    "home": string,
    "away": string,
    "1H1": number,
    "1H2": number,
    "2H1": number,
    "2H2": number,
    "FGT": number,
    "GPM": string,
    "TG1": string,
    "TG2": string,
    "FC": number,
    "RCT1": string,
    "RCT2": string,
    "Bet": string,
    "K1": number,
    "x": number,
    "K2": number,
    "BP1": number | string,
    "BP2": number | string,
    "GA1": number | string,
    "GA2": number | string,
    "SOG1": number | string,
    "SOG2": number | string,
    "OFG1": number | string,
    "OFG2": number | string,
    "BS1": number | string,
    "BS2": number | string,
    "FK1": number | string,
    "FK2": number | string,
    "CK1": number | string,
    "CK2": number | string,
    "OFF1": number | string,
    "OFF2": number | string,
    "TI1": number | string,
    "TI2": number | string,
    "SV1": number | string,
    "SV2": number | string,
    "F1": number | string,
    "F2": number | string,
    "RC1": number | string,
    "RC2": number | string,
    "YS1": number | string,
    "YS2": number | string,
    "TP1": number | string,
    "TP2": number | string,
    "CP1": number | string,
    "CP2": number | string,
    "TKL1": number | string,
    "TKL2": number | string,
    "TA1": number | string,
    "TA2": number | string,
    "DA1": number | string,
    "DA2": number | string
}
